### ISSUE TITLE
Display the author name

### ISSUE THREAD

**Issue by ilyadorosh** [CezaryJurewicz/Egora#8]
I would submit, that displaying author's name on an idea, and it being a link to their IP, will allow users to _explore_ other ideas they have, and giving an incentive for people to author ideas.
Besides, it's just for basic _accountability_.
Somebody in the meeting already pointed out the absence of the author's name, it just feels weird.
I would also add the ability to view everybody that supports the idea.
## Maybe this is the wrong Egora to suggest it to
But someday, either an existing social platform, institution or a startup will create a **complete** solution for direct democracy, with all the features, that Facebook has, but with the real weight on the political process.

**Comment by ilyadorosh** [comment]
It's just a matter of adding 
```php
{{$idea->nation->title}}
```
to the resources/views/blocks/ideas.blade.php
but I guess it's not something on your TODO list.

**Comment by CezaryJurewicz** [comment]
Dude, beautiful.

Wait, so ur not in touch w Ruslan?

Do u want me to connect you?

Should I?

Cezary Jurewicz
Filosofos Vasileus
International Logic Party
"Transparency is the price of power."
***********************
Egora-ILP.org
1-331-666-6968

**Comment by russam** [comment]
I'm not sure if this will fit with the approach that ideas must by anonymous.
@CezaryJurewicz is that right? 
As the alternative we can dispay author's search name here.

**Comment by CezaryJurewicz** [comment]
I have no idea what's going on here. 

I dont know how github works.

 
 

Sent: Monday, November 23, 2020 at 6:45 AM

**Comment by CezaryJurewicz** [comment]
Oh, now i understand. I guess I can reply to the message thread through my email. Cool!

Anyway, ideas do not display authors because the authors aren't important. The supporters are important. And the new version of Egora will display the 100 most recent supporters. We don't want to show all of them to prevent data mining, but we want the newest ones to be shown to engage the newest platform users.
